package com.example.mente_libre_app.navigation

sealed class Route(val path: String) {
    data object Portada : Route("portada")
    data object Cargando : Route("cargando")
    data object Frase : Route("frase")
    data object Bienvenida1 : Route("bienvenida1")
    data object Bienvenida2 : Route("bienvenida2")
    data object Bienvenida3 : Route("bienvenida3")
    data object Bienvenida4 : Route("bienvenida4")
    data object Bienvenida : Route("bienvenida")
    data object Crear : Route("crear")
    data object Objetivo : Route("objetivo")
    data object Genero : Route("genero")
    data object Foto : Route("foto")
    data object Huella : Route("huella")
    data object Tema : Route("tema")
    data object Mascota : Route("mascota")
    data object Selector : Route("selector")
    data object NombrarMascota : Route("nombrar_mascota/{mascota}")
    data object Iniciar : Route("iniciar")
    data object Inicio : Route("inicio")
    data object Puntaje : Route("puntaje")
    data object Animo : Route("animo")
    data object Organizarse : Route("organizarse")
    data object Crisis : Route("crisis")
    data object Estrategias : Route("estrategias")
    data object Salud : Route("salud")
    data object Diario : Route("diario")
    data object LineasAyuda : Route("lineas_ayuda")
    data object Bitacora       : Route("bitacora")
    data object DiarioGratitud: Route("diario_gratitud")
    data object DesafiosSemanales: Route("desafios_semanales")
    data object Ajustes : Route("ajustes")
    data object Perfil : Route("perfil")
    data object EliminarCuenta : Route("eliminar_cuenta")
    data object Seguridad : Route("seguridad")
    data object Reportes : Route("reportes")
    data object Companera : Route("companera")
    data object AdminDashboard : Route("admin_dashboard")
    data object Users : Route("users")
    data object Roles : Route("roles")
    data object CambiarContrasena : Route("cambiar_contrasena")
    data object Compannera : Route("compannera")
    data object Chat : Route("chat")

}